stages:
  load_data:
    cmd: python src/stages/load_data.py
    deps:
      - params.yaml
  train_model:
    cmd: python src/stages/train.py
    deps:
      - params.yaml
  evaluate_model:
    cmd: python src/stages/evaluate.py
    deps:
      - params.yaml
