base:
  random_state: 42
data:
  #loading data config
  train_data: ./data/sign_mnist_train/sign_mnist_train.csv
  test_data: ./data/sign_mnist_test/sign_mnist_test.csv
train:
  #training hyper parameter
  RLP:
    monitor: 'val_accuracy'
    patience: 2
    verbose: 1
    factor: 0.5
    min_lr: 0.00001
  fit:
    batch_size: 128
    epochs: 20
reports:
  # path to store images
  confusion_matrix_image: './reports/confusion_matrix.png'

